name: Installing Git
on: workflow_dispatch

jobs:
  git-job:
    runs-on: ubuntu-latest
    steps:
      - name: Installing git
        run: sudo apt install git -y
      - name: Git version
        run: git --version
      
