name: Git and docker installation
on: workflow_dispatch

jobs:
  Git-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Git install and version
        run: |
          sudo apt install git -y
          git --version
      - name: Docker install
        run: |
          sudo apt install docker -y
          docker -version
          
        
